"""Shadow Mask Distillation Loss: Dual-Track GRPO Loss for KV-Compressed RL.

This module implements the core loss function for Shadow Mask Distillation (SMD),
a method that enables reliable Reinforcement Learning post-training under KV cache
compression. The key insight is that naive KV compression during rollout creates a
fatal off-policy mismatch — the rollout generates tokens under a sparse policy
π_sparse, but the learner assumes they were generated under the dense policy π_dense.
Without correction, this causes complete learning collapse (zero reward).

SMD corrects this via a dual-track loss:

    Total Loss = GRPO_loss(π_shadow) + λ · D_KL(π_dense ‖ stop_grad(π_shadow))

    - Track 1 (Shadow, On-Policy Faithful): Computes the GRPO policy gradient loss
      only on tokens whose KV context was preserved by compression. This ensures the
      gradient signal is computed on tokens that are truly "on-policy" faithful, i.e.,
      their generation distribution matches what a compressed model would have produced.

    - Track 2 (Dense, Knowledge Assimilation): Adds a KL divergence term that forces
      the full dense network to internalize the sparse reasoning pathway. This acts as
      a regularizer that transfers knowledge from the compressed view to the full model.

Reference:
    Shadow Mask Distillation for KV Cache Compression in RL Post-Training

Example Integration (with Slime/Megatron):
    ```bash
    python train.py \\
        --loss-type custom_loss \\
        --custom-loss-function-path smd.shadow_distillation_loss.shadow_distillation_loss_function \\
        --use-shadow-mask \\
        --shadow-retention-ratio 0.5 \\
        --shadow-strategy snapkv \\
        --shadow-distill-lambda 0.1
    ```

Note:
    This loss function is designed as a drop-in replacement for the standard GRPO
    policy_loss. It requires the training framework to pass `shadow_masks` in the
    rollout batch, which are generated by the `ShadowMaskInterceptor`.
"""

import logging
from argparse import Namespace
from collections.abc import Callable
from typing import Any

import torch
import torch.nn.functional as F

logger = logging.getLogger(__name__)


def shadow_distillation_loss_function(
    args: Namespace,
    batch: dict,
    logits: torch.Tensor,
    sum_of_sample_mean: Callable[[torch.Tensor], torch.Tensor],
) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
    """Compute the dual-track Shadow Mask Distillation loss.

    This function replaces the standard GRPO policy loss in the training loop.
    It operates in two tracks:

    1. **Shadow Track (On-Policy):** Restricts the GRPO loss computation to
       tokens that are "on-policy faithful" — i.e., tokens whose KV context
       was fully preserved by the compression mask. Tokens generated under
       a lossy KV view are downweighted to avoid poisoning the gradient.

    2. **Distillation Track (Dense → Sparse):** Computes a KL divergence
       between the dense model's log-probs and the rollout log-probs (which
       serve as a proxy for the sparse policy). This term encourages the dense
       model to align with the compressed reasoning pathway.

    Design Decision — Why not two forward passes?
        Ideally, Track 1 would use a separate forward pass with shadow-masked
        attention. However, most RL training frameworks (e.g., Megatron-LM)
        only execute a single forward pass per training step. Instead, we use
        a post-hoc token-level masking strategy: the shadow_mask identifies
        which tokens' log-probs are trustworthy, and we restrict the loss
        computation to those positions.

    Args:
        args: Training configuration namespace. Expected attributes:
            - eps_clip (float): PPO clipping epsilon (default: 0.2)
            - entropy_coef (float): Entropy bonus coefficient
            - shadow_distill_lambda (float): Weight for Track 2 distillation
            - use_rollout_logprobs (bool): Whether to use rollout log-probs
        batch: Rollout batch dictionary containing:
            - "shadow_masks" (list[Tensor]): Per-sample (T, T) boolean masks
            - "unconcat_tokens", "total_lengths", "response_lengths": Sequence info
            - "rollout_log_probs", "advantages", "loss_masks": GRPO inputs
        logits: Dense forward pass logits, shape (1, T, V)
        sum_of_sample_mean: Aggregation function for distributed training

    Returns:
        Tuple of (total_loss, metrics_dict) where metrics_dict contains:
            - loss: Total combined loss
            - shadow_pg_loss: Track 1 policy gradient loss
            - kl_distill_loss: Track 2 distillation loss
            - shadow_entropy: Entropy of shadow-masked tokens
            - shadow_clipfrac: PPO clip fraction on shadow tokens
            - shadow_token_ratio: Fraction of tokens considered "on-policy"
    """
    # NOTE: These imports are framework-specific (Slime/Megatron).
    # To port SMD to a different framework, replace these with your own
    # implementations of log-prob extraction and standard policy loss.
    from slime.backends.megatron_utils.loss import (
        get_log_probs_and_entropy,
        policy_loss_function,
    )

    # ── Retrieve shadow mask configuration ──────────────────────────────
    shadow_masks = batch.get("shadow_masks", None)
    lambda_distill = getattr(args, "shadow_distill_lambda", 0.1)

    # Graceful fallback: if no shadow masks are present (e.g., dense baseline),
    # behave exactly like standard GRPO policy_loss.
    if shadow_masks is None or not shadow_masks:
        logger.debug("No shadow_masks found, falling back to standard policy_loss")
        return policy_loss_function(args, batch, logits, sum_of_sample_mean)

    # ── Extract log-probs and entropy from dense logits ─────────────────
    response_lengths = batch["response_lengths"]
    total_lengths = batch["total_lengths"]
    max_seq_lens = batch.get("max_seq_lens", None)

    _, log_probs_and_entropy = get_log_probs_and_entropy(
        logits,
        args=args,
        unconcat_tokens=batch["unconcat_tokens"],
        total_lengths=total_lengths,
        response_lengths=response_lengths,
        with_entropy=True,
        max_seq_lens=max_seq_lens,
    )

    log_probs = log_probs_and_entropy["log_probs"]      # list of (resp_len,)
    entropy_list = log_probs_and_entropy["entropy"]

    old_log_probs_list = (
        batch["rollout_log_probs"] if args.use_rollout_logprobs else batch["log_probs"]
    )
    advantages_list = batch["advantages"]
    loss_masks_list = batch["loss_masks"]

    # ── Track 1: Build per-token shadow trustworthiness masks ───────────
    #
    # The shadow_mask is a (total_len, total_len) boolean attention mask.
    # For each response token, we check what fraction of the full KV context
    # it can "see" through the mask. If visibility < 100%, the token was
    # generated under a compressed KV view and is considered "on-policy
    # faithful" (it matches what the compressed model would have produced).
    shadow_token_masks = []
    for i, sm in enumerate(shadow_masks):
        if sm is None:
            shadow_token_masks.append(
                torch.ones(response_lengths[i], dtype=torch.bool, device=logits.device)
            )
            continue

        total_len = total_lengths[i]
        resp_len = response_lengths[i]
        prompt_len = total_len - resp_len

        if sm.shape[0] >= total_len:
            # Extract the response rows of the attention mask
            resp_mask = sm[prompt_len:total_len, :total_len]  # (resp_len, total_len)
            visibility_ratio = resp_mask.float().sum(dim=-1) / total_len
            # Tokens with visibility < 1.0 were generated under compression
            shadow_token_masks.append(
                (visibility_ratio < 1.0).to(logits.device)
            )
        else:
            shadow_token_masks.append(
                torch.ones(resp_len, dtype=torch.bool, device=logits.device)
            )

    # ── Track 1: GRPO Loss on shadow-faithful tokens only ───────────────
    pg_losses = []
    pg_clipfracs = []
    shadow_entropies = []

    for i in range(len(log_probs)):
        lp = log_probs[i]
        old_lp = old_log_probs_list[i]
        adv = advantages_list[i]
        lm = loss_masks_list[i]
        stm = shadow_token_masks[i] if i < len(shadow_token_masks) else torch.ones_like(lm, dtype=torch.bool)

        # Combine the original loss mask with the shadow trustworthiness mask.
        # Only tokens that are BOTH valid (loss_mask=1) AND on-policy faithful
        # (shadow_token_mask=1) contribute to the gradient.
        effective_mask = lm.float() * stm.float().to(lm.device)

        # Standard PPO-style clipped surrogate objective
        ratio = torch.exp(lp - old_lp)
        pg_loss1 = -adv * ratio
        pg_loss2 = -adv * torch.clamp(ratio, 1.0 - args.eps_clip, 1.0 + args.eps_clip)
        pg_loss = torch.max(pg_loss1, pg_loss2)

        pg_loss = pg_loss * effective_mask
        clipfrac = ((ratio - 1.0).abs() > args.eps_clip).float() * effective_mask

        pg_losses.append(pg_loss)
        pg_clipfracs.append(clipfrac)

        if i < len(entropy_list):
            shadow_entropies.append(entropy_list[i] * effective_mask)

    pg_loss_cat = torch.cat(pg_losses, dim=0)
    pg_clipfrac_cat = torch.cat(pg_clipfracs, dim=0)

    shadow_pg_loss = sum_of_sample_mean(pg_loss_cat)
    shadow_clipfrac = sum_of_sample_mean(pg_clipfrac_cat)

    shadow_entropy = torch.tensor(0.0, device=logits.device)
    if shadow_entropies:
        shadow_entropy = sum_of_sample_mean(torch.cat(shadow_entropies, dim=0))

    # ── Track 2: Dense → Sparse KL Distillation ────────────────────────
    #
    # Since we only have one forward pass (dense), we cannot obtain independent
    # π_shadow logits. Instead, we use the rollout log-probs as the shadow
    # target — they represent the token-level distribution under sparse KV.
    #
    # The distillation signal: |log π_dense(t) - log π_sparse(t)|
    # This absolute difference serves as a token-level alignment objective.
    kl_distill_loss = torch.tensor(0.0, device=logits.device)
    if lambda_distill > 0 and "rollout_log_probs" in batch and batch["rollout_log_probs"]:
        dense_lp = torch.cat(log_probs, dim=0)
        shadow_target_lp = torch.cat(batch["rollout_log_probs"], dim=0).to(logits.device)

        kl_per_token = (dense_lp - shadow_target_lp).abs()
        kl_distill_loss = sum_of_sample_mean(kl_per_token)

    # ── Combine: Total Loss ─────────────────────────────────────────────
    total_loss = shadow_pg_loss - args.entropy_coef * shadow_entropy + lambda_distill * kl_distill_loss

    # Ensure gradient flow even with empty sequences
    if torch.cat(log_probs, dim=0).numel() == 0:
        total_loss += 0 * logits.sum()

    # ── Metrics for monitoring ──────────────────────────────────────────
    metrics = {
        "loss": total_loss.clone().detach(),
        "shadow_pg_loss": shadow_pg_loss.clone().detach(),
        "shadow_entropy": shadow_entropy.clone().detach(),
        "shadow_clipfrac": shadow_clipfrac.clone().detach(),
        "kl_distill_loss": kl_distill_loss.clone().detach(),
        "distill_lambda": torch.tensor(lambda_distill, device=logits.device),
    }

    # Track the fraction of tokens considered on-policy faithful
    if shadow_token_masks:
        all_stm = torch.cat([stm.float() for stm in shadow_token_masks])
        metrics["shadow_token_ratio"] = all_stm.mean().detach()

    return total_loss, metrics
